use crate::day_13::Layer;

pub const INPUT: &[Layer] = &[
    Layer { depth: 0, range: 3 },
    Layer { depth: 1, range: 2 },
    Layer { depth: 2, range: 4 },
    Layer { depth: 4, range: 4 },
    Layer { depth: 6, range: 5 },
    Layer { depth: 8, range: 8 },
    Layer { depth: 10, range: 6 },
    Layer { depth: 12, range: 6 },
    Layer { depth: 14, range: 8 },
    Layer { depth: 16, range: 6 },
    Layer { depth: 18, range: 6 },
    Layer { depth: 20, range: 8 },
    Layer { depth: 22, range: 12 },
    Layer { depth: 24, range: 8 },
    Layer { depth: 26, range: 8 },
    Layer { depth: 28, range: 12 },
    Layer { depth: 30, range: 8 },
    Layer { depth: 32, range: 12 },
    Layer { depth: 34, range: 9 },
    Layer { depth: 36, range: 14 },
    Layer { depth: 38, range: 12 },
    Layer { depth: 40, range: 12 },
    Layer { depth: 42, range: 12 },
    Layer { depth: 44, range: 14 },
    Layer { depth: 46, range: 14 },
    Layer { depth: 48, range: 10 },
    Layer { depth: 50, range: 14 },
    Layer { depth: 52, range: 12 },
    Layer { depth: 54, range: 14 },
    Layer { depth: 56, range: 12 },
    Layer { depth: 58, range: 17 },
    Layer { depth: 60, range: 10 },
    Layer { depth: 64, range: 14 },
    Layer { depth: 66, range: 14 },
    Layer { depth: 68, range: 12 },
    Layer { depth: 70, range: 12 },
    Layer { depth: 72, range: 18 },
    Layer { depth: 74, range: 14 },
    Layer { depth: 78, range: 14 },
    Layer { depth: 82, range: 14 },
    Layer { depth: 84, range: 24 },
    Layer { depth: 86, range: 14 },
    Layer { depth: 94, range: 14 },
];
